---
name: UnitTest
on:
  push:
    branches:
      - master

jobs:
  source-tests:
    name: Unit-tests
    runs-on: ubuntu-latest
          
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'alpine:edge'
          - 'centos:7'
          - 'centos:8'
          - 'debian:9'
          - 'fedora:32'
          - 'fedora:33'
          - 'ubuntu:16.04'
          - 'ubuntu:18.04'
          - 'ubuntu:20.04'
          - 'ubuntu:20.10'
        include:
          - distro: 'alpine:edge'
            pre: 'apk add -U bash'
    steps:
      - name: "Git clone repo"
        uses: actions/checkout@v2
      - name: Setup bash releases
        uses: actions/cache@v2.1.3
        with:
          path: tests/bash_source/releases/bash-*/bin/bash
          key: bash-releases-${{ matrix.distro }}
          restore-keys: |
            bash-releases-${{ matrix.distro }}
              
      - name: run-test-all.sh on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep.sh
          bash ./prep.sh
          ./tests/test_all.sh
